### ISSUE TITLE
Concurrency Patterns

### ISSUE THREAD

**Issue by mattfiocca** [johnnadratowski/golang-neo4j-bolt-driver#13]
I realize this is more of a question for stack overflow, but thought i'd reach out to you all on this particular package in terms of connecting to Neo4j with high concurrency.

We have to chew through about a million and a half xml files for consumption into our graph. The problem is that with our queue system we've built for processing XML files into Neo queries, we keep running into neo connection peer resets and what not, even when throttling our routines down to just 100 or so workers.

Here is an upper level of our current process:

Walking a file tree to build up a queue of files to process (+/- 1.27million files), then after the walk is done, we iterate that queue and fire off go routines to process each file, using a buffered throttle channel to block the spawning of new routines until previous routines have finished. Within each routine i'm spinning up a new neo connection, prepare statement, execute, close, etc.. Each xml file/process represents a single node with properties that needs to be imported into the graph. As i mentioned, our buffered channel is down to about 100 workers at one time, and we are still seeing neo connection resets and timeouts.

If it would be appropriate to ask for any architectural recommendations here, using this package, i'd greatly appreciate the help. 

I see that this package offers Pipelines, but am really not sure how to leverage that feature within the queue workers that we already have for processing our XML.

Thanks in advance

**Comment by johnnadratowski** [comment]
@mattfiocca - Sorry for the late response, I've been really busy in my personal life.

This is a really good question, but I do agree that this might not be the best forum for it.  I'll do my best to answer you, however.

I can't speak too much to how Neo4J manages its connections.  I cannot say for sure what is causing the resets.

I can speak to what I've seen when developing the driver.  I had an issue from another engineer a while back where they wanted to use the Pipelining support to run a massive amount of statements at once (think in the tens to hundreds of thousands).  While the driver wasn't necessarily choking on this, he was seeing timeouts occur. 

To the best of my knowledge, these timeouts occurred simply because Neo4j just took longer than the timeout time to process his massive pipeline request.

In your case, you might be hitting something similar.  Your workers might be creating so much work for Neo4J that it's unable to respond in the timeout time given.

In your case, Pipelining may help.  Pipelining simply allows you to send multiple queries to Neo4j that will happen concurrently.  I could see the most optimal solution for your situation being something like:

1. Tune down the "workers" to 20
2. Every worker "pipelines" 5 queries at once
3. With no timeout on the connection

I'm not saying that is the most optimal solution.  Maybe it's worse.  I don't know, and I don't have enough knowledge of Neo4j internals to tell you definitively.

Hope this helps.

**Comment by johnnadratowski** [comment]
I'm also closing this issue since it isn't necessarily an issue with the driver.
