### ISSUE TITLE
Not able to connect to GrapheneDB.com

### ISSUE THREAD

**Issue by mpmlj** [johnnadratowski/golang-neo4j-bolt-driver#5]
Hi guys,

Was not able to connect to my GrapheneDB.com sandbox account (non-TLS) with your driver, however could connect locally.
This is also confirmed by one of the GrapheneDB.com specialists.

(Also posted in the "bolt-go-driver" channel of neo4j's Slack)

**Comment by johnnadratowski** [comment]
@mpmlj - I looked into this.  It seems the errors you were getting were because GrapheneDB does, in fact, use TLS.

I decided to go ahead and implement TLS functionality in the library: https://github.com/johnnadratowski/golang-neo4j-bolt-driver/pull/7

I documented how to use it - you give the connection string some query params for TLS.  When I created a GrapheneDB sandbox for myself, it worked with simply using `?tls=true`.

I also decided to write a blog post about this: http://johnnadratowski.github.io/2016/08/05/golang-tls.html

Another really good thing about this was that it found a gap in my testing.  I was always using a local Neo4j DB for my tests.  The problem with that was that there is some lag when you have a remote server, so I had to add some logic to keep pulling from the stream when decoding if only getting a partial message. 

Thanks for the issue, definitely helped push forward the project!

**Comment by jexp** [comment]
Really cool, thanks a lot.

**Comment by jexp** [comment]
@johnnadratowski perhaps close this issue? :)

**Comment by johnnadratowski** [comment]
@jexp - agreed, I have been able to successfully connect to GrapheneDB from both my local and a Heroku instance. Closing.

**Comment by ronpastore** [comment]
ahhh this just helped me big time! thanks. @johnnadratowski maybe good to add to README, ?tls=true. was a while before i realized "connection reset by peer" was TLS related. was on heroku/graphene where TLS is forced. like @jexp, everything seemingly worked locally and on server i had isConnected=true..  thanks again!
